@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNzkiLCJnaXZlbl9uYW1lIjoibWVkaWNvX2NpZWdvZGVhdmlsYV8xNSIsImp0aSI6ImUyMTlhNTM4LTRkMDMtNDBiMy1hOGQ5LWYwMTRlMmUzZjkzMyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lZGljYWxSZXZpZXdlciIsImV4cCI6MTc3NzY5NzE2OCwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.z6U8aWgoUkQ_WfT3Cl6NIYLZ13W9RbpIrGqheGt71q0


POST {{host}}/api/MedicalReview
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "reportId": "08dea7fc-5213-4e15-81b6-9d52cf47bcf9",
  "causality": "Probable",
  "clinicalSignificance":"ExpectedEvent",
  "reviewedAt": "2026-04-06T11:38:12.913Z",
  "clinicalMedicalReviews": [
    {
      "adverseEventId": "08dea7fc-5213-4ee7-856b-767d50bac5a0",
      "laboratoryResults": "Evaluacion no arroja nada",
      "medDRACode": "23232323",
      "retClassification": "Posiblemente nada"
    }
  ]
}

