@host = http://localhost:5137

# MedicalReviewer
POST {{host}}/api/Authentication/login
Content-Type:  application/json

{
  "email": "pablo@example.com",
  "password": "Password_123!"
}


####
# SectionResponsible
POST {{host}}/api/Authentication/login
Content-Type:  application/json

{
  "email": "pedro1@example.com",
  "password": "Password_123!"
}



