@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsImdpdmVuX25hbWUiOiJwZWRybzEiLCJqdGkiOiI5YTk3YTE2Ny1kZDhmLTRhOWItOWY5Yi1mNjBhYjBlNmM5ZjUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTZWN0aW9uUmVzcG9uc2libGUiLCJleHAiOjE3NzQwNTMxNDgsImlzcyI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UiLCJhdWQiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIn0.s8zQwFHribJwfZx8zE6ZQxyrGtQd9wGsfXjs1634Whs
POST {{host}}/api/MedicalReviewer/register
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "fullname": "Pablo",
  "userName": "Pablo",
  "email": "pablo@example.com",
  "password": "Password_123!",
  "dateOfBirth": "1986-01-20T22:54:04.023Z",
  "gender": 0,
  "healthArea": "Consultorio de Centro Habana",
  "phoneNumber": "55664266",
  "municipalityId": 1
}

####
POST {{host}}/api/SectionResponsible/register
Content-Type:  application/json

{
  "fullname": "Pedro",
  "userName": "pedro1",
  "email": "pedro1@example.com",
  "password": "Password_123!",
  "userRole": "SectionResponsible",
  "provinceId": 1
}


