@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImFkbWluX3VzZXJuYW1lXzEiLCJqdGkiOiIwNGI4MDllMy1jZjUwLTQwNzgtYjRmMC03ZDk5ZTNiYzQ4NTEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NzQ0NTQxNiwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.IknvV4bM6U9jwHUThi9WWArTMWxQCp-0QdowtbW3qq0

GET {{host}}/api/GetCatalog/vaccine?pageNumber=1&pageSize=10
Content-Type:  application/json
Authorization: Bearer {{token}}



####

GET {{host}}/api/GetCatalog/symptom?pageNumber=1&pageSize=10&search=&status=
Content-Type:  application/json
Authorization: Bearer {{token}}




####


GET http://localhost:5137/api/GetCatalog/symptom?pageNumber=1&pageSize=10
Content-Type:  application/json
Authorization: Bearer {{token}}



### 
POST {{host}}/api/Catalog/activate/symptom/1
Content-Type:  application/json
Authorization: Bearer {{token}}



####


GET http://localhost:5137/api/GetCatalog/vaccines/actives
Content-Type:  application/json