@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZ2l2ZW5fbmFtZSI6InVzZXJuYW1lXzEiLCJqdGkiOiI2MGUxMjUxYS1lN2U5LTRmMGUtYmViOC1hODE5ZDM0MDU3ZDMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NTY3NDIwOSwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.9JhVAWl7kwUnJvPgmAp9z9692fell6CtUZblCyKr9gI

POST {{host}}/api/Catalog/register/symptom
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "name": "Fiebre",
  "standardCode": "12121223",
  "codingSystem": "12312312",
  "category": "General",
  "isActive": true,
  "description": "Elevación de la temperatura corporal por encima de lo normal, comúnmente asociada a infecciones o inflamaciones."
}
