@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZ2l2ZW5fbmFtZSI6InVzZXJuYW1lXzEiLCJqdGkiOiI2MGUxMjUxYS1lN2U5LTRmMGUtYmViOC1hODE5ZDM0MDU3ZDMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NTY3NDIwOSwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.9JhVAWl7kwUnJvPgmAp9z9692fell6CtUZblCyKr9gI

POST {{host}}/api/Catalog/register/vaccine
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "name": "Soberana 02",
  "type": 0,
  "code": "TC12323",
  "isActive": true,
  "description": "A vaccine developed by the Finlay Institute in Cuba, based on a recombinant protein subunit platform. It has shown efficacy in preventing symptomatic COVID-19 and severe disease.",
  "approvalDate": "2026-04-03T09:18:28.095Z"
}

