@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkphYmVsIiwianRpIjoiMmQ5NTc3ZWYtNDFkOS00ZmY0LTk3YmUtNmNhNzFmMDU0MzUwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NzUxODY5NTcsImlzcyI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UiLCJhdWQiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIn0.EeXLGSZZ5ZhaRVt98vKbMQdEvCXSs6GozuoEdO5d_Hw

POST {{host}}/api/Catalog/register/vaccine
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "name": "AbDAlA",
  "type": 0,
  "code": "TC12323",
  "isActive": true,
  "description": "A vaccine developed by the Finlay Institute in Cuba, based on a recombinant protein subunit platform. It has shown efficacy in preventing symptomatic COVID-19 and severe disease.",
  "approvalDate": "2026-04-02T22:18:28.095Z"
}

