@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImNhcmxvcyIsImp0aSI6IjAzZDZjOTJlLTQ1ZjMtNDBmNS1hZGM1LTI2MDYzNDFhNzk5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NDQwMzQ1LCJpc3MiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIiwiYXVkIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSJ9.GO0kFthrcL53ray8U41o4CM2zbdog6MVKRrPuvq34T0

POST {{host}}/api/Catalog/register/vaccine
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "name": "Abdala",
  "type": 0,
  "code": "TC12323",
  "isActive": true,
  "description": "A vaccine developed by the Finlay Institute in Cuba, based on a recombinant protein subunit platform. It has shown efficacy in preventing symptomatic COVID-19 and severe disease.",
  "approvalDate": "2026-04-03T09:18:28.095Z"
}

