@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDIiLCJnaXZlbl9uYW1lIjoibWVkaWNvX21hcmllbF83IiwianRpIjoiZDZiZGVhOTgtZDEwMy00NDUzLWE5MzctZGY1MTRmMmY4OGFkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWVkaWNhbFJldmlld2VyIiwiZXhwIjoxNzc3NDI0MTkzLCJpc3MiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIiwiYXVkIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSJ9.TJNgf5qTuUFmx_MdDb1CT9IkXkEf2h56-ugwiXwzjAs

GET {{host}}/api/Report/get-report-assigment?pageNumber=1&pageSize=10
Content-Type:  application/json
Authorization: Bearer {{token}}

