@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MyIsImdpdmVuX25hbWUiOiJtZWRpY29fcGluYXJkZWxyaW9fOCIsImp0aSI6IjdkZjkxYzE5LTc3YzAtNDg1My04MzUxLWI0ODE2M2YyNTE0OCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lZGljYWxSZXZpZXdlciIsImV4cCI6MTc3NzQ5MTEzMSwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.7DPNiAJFYAoMuUmp8UKammpBpnhEw-XM938agX1ThkM


GET {{host}}/api/Report/get-report-assigment?pageNumber=1&pageSize=10
Content-Type:  application/json
Authorization: Bearer {{token}}



