@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZ2l2ZW5fbmFtZSI6Ikp1bGlvIiwianRpIjoiNTQwNDc3MzctZWUzZS00OTVhLWIzNzItYzRmMGRjODVmMWVjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2VjdGlvblJlc3BvbnNpYmxlIiwiZXhwIjoxNzc2ODk5NDc5LCJpc3MiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIiwiYXVkIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSJ9.VVg6d9Z6qI6yUTEMOZy4nCT8R1UT34t5YlY7G_6uw60

POST {{host}}/api/MedicalReviewAssignment/create
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "medicalReviewerId": "08dea0bc-664b-463e-8c24-4b0ba0225684",
  "aefiReportId": "08dea0bb-b9d8-4d63-8156-b622656ed5f8",
  "assignedAt": "2026-04-05T22:10:30.680Z"
}

