@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsImdpdmVuX25hbWUiOiJKdWxpbyIsImp0aSI6IjRmZmU4YjgxLTkzMjEtNGM1OC04NDQyLWM0YmZjYzIwNzE4MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNlY3Rpb25SZXNwb25zaWJsZSIsImV4cCI6MTc3NjI5MzQ3MywiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.A4p9ISlNlqLLJEJ0vIe5XW9oKuz_AqOTXtkojYkeGKA

POST {{host}}/api/MedicalReviewAssignment/create
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "medicalReviewerId": 1,
  "aefiReportId": 1,
  "assignedAt": "2026-04-05T22:10:30.680Z"
}

