@host = http://localhost:5137

# MedicalReviewer
POST {{host}}/api/Report/createPublic
Content-Type:  application/json

{
  "reportDate": "2026-04-03T14:13:59.418Z",
  "reporter": {
    "fullName": "Jabel",
    "reporterRelationship": 0,
    "identityNumber": "03041868161",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "provinceId": 1,
    "municipalityId": 1,
    "phoneNumber": "55664266",
    "email": "jabel@example.com",
    "professionalLicense": "string",
    "institution": "string"
  },
  "vaccinatedSubject": {
    "fullName": "Jabel",
    "identityNumber": "03041868161",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "gender": 0,
    "isPregnant": false,
    "provinceId": 1,
    "municipalityId": 1,
    "healthArea": "string",
    "address": "string",
    "phoneNumber": "55664266",
    "email": "jabel@example.com",
    "currentMedications": "string",
    "allergies": "string",
    "medicalHistory": "string"
  },
  "vaccinations": [
    {
      "vaccineId": 1,
      "batchNumber": "qweqweq",
      "site": 0,
      "doseNumber": 2,
      "administrationDate": "2026-04-02T18:13:59.418Z",
      "vaccinationCenter": "string"
    },
    {
      "vaccineId": 2,
      "batchNumber": "qweqweq",
      "site": 0,
      "doseNumber": 2,
      "administrationDate": "2026-04-02T18:13:59.418Z",
      "vaccinationCenter": "string"
    },
    {
      "vaccineId": 3,
      "batchNumber": "qweqweq",
      "site": 0,
      "doseNumber": 2,
      "administrationDate": "2026-04-02T18:13:59.418Z",
      "vaccinationCenter": "string"
    }
  ],
  "adverseEvents": [
    {
      "startDate": "2026-04-03T12:13:59.418Z",
      "description": "string",
      "visitedDoctor": true,
      "wentToEmergencyRoom": true,
      "permanentDisability": true,
      "isLifeThreatening": true,
      "resultedInDeath": true,
      "deathDate": "2026-04-03T12:16:59.418Z",
      "currentStatus": 0,
      "laboratoryResults": "string",
      "medDRACode": "string",
      "retClassification": "string",
      "symptoms": [
        1,2,3
      ]
    }
  ]
}