@host = http://localhost:5137

# MedicalReviewer
POST {{host}}/api/Report/createPublic
Content-Type:  application/json

{
  "reportDate": "2026-04-04T19:13:59.418Z",
  "reporter": {
    "fullName": "Jabel",
    "reporterRelationship": 2,
    "identityNumber": "03041868163",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "provinceId": 1,
    "municipalityId": 1,
    "phoneNumber": "55664266",
    "email": "jabel@example.com",
    "professionalLicense": "string",
    "institution": "string"
  },
  "vaccinatedSubject": {
    "fullName": "Jabel",
    "identityNumber": "03041868190",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "gender": 1,
    "isPregnant": false,
    "provinceId": 1,
    "municipalityId": 1,
    "healthArea": "string",
    "address": "string",
    "phoneNumber": "55664266",
    "email": "jabel@example.com",
    "currentMedications": "string",
    "allergies": "string",
    "medicalHistory": "string"
  },
  "vaccinations": [
    {
      "vaccineId": 1,
      "batchNumber": "qweqweq",
      "site": 3,
      "doseNumber": 5,
      "administrationDate": "2026-04-02T18:13:59.418Z",
      "vaccinationCenter": "string"
    }
  ],
  "adverseEvents": [
    {
      "startDate": "2026-04-03T12:13:59.418Z",
      "description": "string",
      "resultedInDeath": false,
      "currentStatus": 2,
      "symptoms": [
        1,2,3
      ]
    },
    {
      "startDate": "2026-04-03T12:13:59.418Z",
      "description": "string",
      "resultedInDeath": false,
      "currentStatus": 2,
      "symptoms": [
        2,3
      ]
    }
  ]
}