@host = http://localhost:5137
@token = 
GET {{host}}/api/User
Content-Type:  application/json

{
  "name": "Jabel",
  "userName": "JabelRA",
  "email": "jabel@example.com",
  "password": "Password_123!",
  "userRole": "Supervisor"
}