@host = http://localhost:5137

POST {{host}}/api/Authentication/register
Content-Type:  application/json

{
  "name": "Eduardo",
  "userName": "eduardo",
  "email": "eduardo@example.com",
  "password": "Password_123!",
  "userRole": "Supervisor"
}