@host = https://backend-production-1e7c9.up.railway.app

POST {{host}}/api/Authentication/register
Content-Type:  application/json

{
  "name": "Jabel",
  "userName": "JabelRA",
  "email": "jabel@example.com",
  "password": "Password_123!",
  "userRole": "Supervisor"
}